[package]
name = "compilador"
version = "0.1.0"
authors = ["MBaltz <mateusbaltazar9@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prettytable-rs = "^0.10"
colored = "^1.8"
