name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cd compilador; cargo build --verbose; cd ..
    - name: Run tests
      run: cd compilador; cargo test --verbose; cd ..
